-- MySQL Script generated by MySQL Workbench
-- Fri Aug 11 13:26:40 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema escoladb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema escoladb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `escoladb` DEFAULT CHARACTER SET utf8 ;
USE `escoladb` ;

-- -----------------------------------------------------
-- Table `escoladb`.`aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escoladb`.`aluno` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `prontuario` INT NOT NULL,
  `data_nascimento` DATE NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `prontuario_UNIQUE` (`prontuario` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escoladb`.`professor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escoladb`.`professor` (
  `id` INT NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `prontuario` VARCHAR(45) NOT NULL,
  `data_nascimento` DATE NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `prontuario_UNIQUE` (`prontuario` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escoladb`.`curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escoladb`.`curso` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `sigla` VARCHAR(5) NOT NULL,
  `duracao` TINYINT UNSIGNED NOT NULL,
  `tipo_duracao` ENUM('semestre', 'enum') NOT NULL,
  `periodo` ENUM('matutino', 'vespertino', 'noturno', 'integral') NOT NULL,
  `data_inicio` DATE NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escoladb`.`disciplina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escoladb`.`disciplina` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `sigla` VARCHAR(5) NOT NULL,
  `semestre` TINYINT NULL,
  `aulas_semana` INT NULL,
  `aulas_total` INT NULL,
  `area` VARCHAR(45) NULL,
  `curso_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_disciplina_curso1_idx` (`curso_id` ASC) VISIBLE,
  CONSTRAINT `fk_disciplina_curso1`
    FOREIGN KEY (`curso_id`)
    REFERENCES `escoladb`.`curso` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escoladb`.`aluno_curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escoladb`.`aluno_curso` (
  `aluno_id` INT NOT NULL,
  `curso_id` INT UNSIGNED NOT NULL,
  `situacao` VARCHAR(45) NOT NULL,
  `data_matricula` DATETIME NOT NULL,
  PRIMARY KEY (`aluno_id`, `curso_id`),
  INDEX `fk_aluno_has_curso_curso1_idx` (`curso_id` ASC) VISIBLE,
  INDEX `fk_aluno_has_curso_aluno_idx` (`aluno_id` ASC) VISIBLE,
  CONSTRAINT `fk_aluno_has_curso_aluno`
    FOREIGN KEY (`aluno_id`)
    REFERENCES `escoladb`.`aluno` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_aluno_has_curso_curso1`
    FOREIGN KEY (`curso_id`)
    REFERENCES `escoladb`.`curso` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escoladb`.`aluno_disciplina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escoladb`.`aluno_disciplina` (
  `aluno_id` INT NOT NULL,
  `disciplina_id` INT UNSIGNED NOT NULL,
  `situacao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`aluno_id`, `disciplina_id`),
  INDEX `fk_aluno_has_disciplina_disciplina1_idx` (`disciplina_id` ASC) VISIBLE,
  INDEX `fk_aluno_has_disciplina_aluno1_idx` (`aluno_id` ASC) VISIBLE,
  CONSTRAINT `fk_aluno_has_disciplina_aluno1`
    FOREIGN KEY (`aluno_id`)
    REFERENCES `escoladb`.`aluno` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_aluno_has_disciplina_disciplina1`
    FOREIGN KEY (`disciplina_id`)
    REFERENCES `escoladb`.`disciplina` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escoladb`.`turma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escoladb`.`turma` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `codigo` CHAR(2) NOT NULL,
  `disciplina_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_turma_disciplina1_idx` (`disciplina_id` ASC) VISIBLE,
  CONSTRAINT `fk_turma_disciplina1`
    FOREIGN KEY (`disciplina_id`)
    REFERENCES `escoladb`.`disciplina` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escoladb`.`aluno_turma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escoladb`.`aluno_turma` (
  `aluno_id` INT NOT NULL,
  `turma_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`aluno_id`, `turma_id`),
  INDEX `fk_aluno_has_turma_turma1_idx` (`turma_id` ASC) VISIBLE,
  INDEX `fk_aluno_has_turma_aluno1_idx` (`aluno_id` ASC) VISIBLE,
  CONSTRAINT `fk_aluno_has_turma_aluno1`
    FOREIGN KEY (`aluno_id`)
    REFERENCES `escoladb`.`aluno` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_aluno_has_turma_turma1`
    FOREIGN KEY (`turma_id`)
    REFERENCES `escoladb`.`turma` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escoladb`.`professor_turma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escoladb`.`professor_turma` (
  `professor_id` INT NOT NULL,
  `turma_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`professor_id`, `turma_id`),
  INDEX `fk_professor_has_turma_turma1_idx` (`turma_id` ASC) VISIBLE,
  INDEX `fk_professor_has_turma_professor1_idx` (`professor_id` ASC) VISIBLE,
  CONSTRAINT `fk_professor_has_turma_professor1`
    FOREIGN KEY (`professor_id`)
    REFERENCES `escoladb`.`professor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_professor_has_turma_turma1`
    FOREIGN KEY (`turma_id`)
    REFERENCES `escoladb`.`turma` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escoladb`.`sala`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escoladb`.`sala` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NULL,
  `computadores` INT NULL,
  `projetor` TINYINT NULL,
  `lousa_digital` VARCHAR(45) NULL,
  `bloco` VARCHAR(45) NULL,
  `andar` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escoladb`.`sala_turma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escoladb`.`sala_turma` (
  `sala_aula_id` INT UNSIGNED NOT NULL,
  `turma_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`sala_aula_id`, `turma_id`),
  INDEX `fk_sala_aula_has_turma_turma1_idx` (`turma_id` ASC) VISIBLE,
  INDEX `fk_sala_aula_has_turma_sala_aula1_idx` (`sala_aula_id` ASC) VISIBLE,
  CONSTRAINT `fk_sala_aula_has_turma_sala_aula1`
    FOREIGN KEY (`sala_aula_id`)
    REFERENCES `escoladb`.`sala` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sala_aula_has_turma_turma1`
    FOREIGN KEY (`turma_id`)
    REFERENCES `escoladb`.`turma` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
